### ISSUE TITLE
Add convenience to creating a downloader job for a single batch.

### ISSUE THREAD

**Issue by kurtwheeler** [data-refinery/data_refinery#14]
As per @mhuyck's comment [here](https://github.com/data-refinery/data_refinery/pull/12#discussion_r119378085) the DownloaderJob model can take a batch as an optional argument and add it to the DownloaderJobsToBatches table.

**Comment by kurtwheeler** [comment]
@mhuyck I've come up with the following function to do handle this issue. I wasn't able to add it as part of the `__init__` function like I had originally thought I might because the DownloaderJob has to be saved before it can be saved as a foreign key to the DownloaderJobsToBatches table. Do you think this is about the best that can be done or do you know of any helpful tricks. (Maybe @rzelayafavila or @dongbohu might also have good input?)

```
    @classmethod
    def create_job_and_relationships(*args, **kwargs):
        """Inits and saves a job, its batches, and the relationships.

        Creates and saves a single DownloaderJob. For each batch
        passed in via the 'batches' keyword, saves that batch, creates
        a DownloaderJobsToBatches record, and saves that record.
        """
        batches = kwargs.pop('batches', None)
        this_job = super().__init__(*args, **kwargs)
        if batches is None:
            raise KeyError("The 'batches' argument must be specified.")
        else:
            this_job.save()
            for batch in batches:
                batch.save()
                downloader_job_to_batch = DownloaderJobsToBatches(batch=batch,
                                                                  downloader_job=this_job)
                downloader_job_to_batch.save()
```

**Comment by mhuyck** [comment]
👍 

I don't know any special tricks for making `__init__` do what we thought. It makes sense that you'd need to have the `.save` done first so there's a bit of an initialization chicken and egg issue there.

My primary observation during that code review was that a one-line object initialization was getting replaced with a template-like block of code in a bunch of places, so if this helper function can streamline that you'll end up with more DRY code and all the bounty that comes with that.

**Comment by kurtwheeler** [comment]
Yup I definitely feel that for sure.

**Comment by kurtwheeler** [comment]
Addressed by https://github.com/data-refinery/data_refinery/pull/26
